
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwbqqljmmsvfrsteuwda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3YnFxbGptbXN2ZnJzdGV1d2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjUwMDYsImV4cCI6MjA2NTc0MTAwNn0.b5GFfl8WcIcnkmr82oM6Kx5ZBlI5LkVxxuGjcIaiJ6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
